version: "3.8"

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "crypto"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
